### ISSUE TITLE
Export excel succeeded,but can't open the file.

### ISSUE THREAD

**Issue by imyundong** [PomeloFoundation/dotNETCore-Extensions#10]
My system version is win10,office version is 2013.Unit test is passed.
![image](https://cloud.githubusercontent.com/assets/9474811/20252126/799c765e-aa5a-11e6-99be-7adda09ab4e4.png)
![image](https://cloud.githubusercontent.com/assets/9474811/20252127/7edcc63c-aa5a-11e6-9aca-42acbad99d3b.png)

**Comment by Kagamine** [comment]
Which `Pomelo.Data.Excel` version are you using?

**Comment by imyundong** [comment]
last version

**Comment by toralux** [comment]
Should be fixed in pull request #11

**Comment by Kagamine** [comment]
Shipped in 10025
